name: Common CI

on:
  workflow_call:
    inputs:
      tag:
        required: false
        type: string

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      TAG: ${{ inputs.tag }}
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0  # Gets all history - yes it's slower but it just works
    - uses: actions/setup-go@v6
      with:
        go-version: '1.25'
    - run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
    - name: Lint
      run: make lint
    - name: Test
      run: make test
    - name: Coverage report
      run: make coverage
    - name: Build Docker image
      run: make docker-build
